### ISSUE TITLE
How Can Add Referer Header For Multiple Target

### ISSUE THREAD

**Issue by Phoenix1112** [projectdiscovery/httpx#533]
thanks for this project. When I try all the url addresses in urls.txt, I need to send each of the subdomain name with a referer header. I can only add a referer header with the -H parameter. Whatever url name is tried in the url list, it will automatically add it to the referer header and send the request that way. how can I do that.?

```
https://www.google.com     > Referer: https://www.google.com
https://www.facebook.com   > Referer: https://www.facebook.com
```

**Comment by ehsandeep** [comment]
@Phoenix1112 You can use nuclei for this, this can not be achieved or supported with httpx

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    headers:
      Referer: "{{RootURL}}"
```
